prompters:
- after: " "
  before: "  | "
  bgcolor: blue
  fgcolor: default
  kind: hostname
  side: left
- after: " "
  before: "  | "
  bgcolor: blue
  fgcolor: default
  kind: username
- before: "  | "
  after: " "
  mode: elided
  bgcolor: dark-gray
  fgcolor: default
  separator: "/"
  side: left
  kind: path